[package]
name = "certstream-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.26.4"
ctrlc = "3.2.2"
redis = "0.21.5"
serde = "1.0.137"
serde_derive = "1.0.137"
serde_json = "1.0.81"
itertools = "*"